name: Project Automation
on:
  pull_request:
    types: [ opened, edited, synchronize, closed ]

jobs:
  project-pr-automation:
    if: github.event.sender.type != 'Bot'
    uses: chTestORG/org-issues/.github/workflows/project-workflows.yml@master
    secrets: inherit